# Generated by Django 4.2.1 on 2023-06-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_current_price_stock_c_rename_change_stock_d_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
